### ISSUE TITLE
more Pins

### ISSUE THREAD

**Issue by pici** [adafruit/Adafruit-Trinket-M0-PCB#1]
I would love to have more output pins.
In my special case i wanna use SPI and I2C together. 
What came in my mind when i look at  the great pcb design was: who needs these drill holes ?
Skip them and you have space for some extra (4) pins !
Would be great !

**Comment by DirtyEngineer** [comment]
Check out the Tau by Rabid Prototypes.  It uses the ATSAMD21E17 chip which is just the smaller sibling (half the flash/ram) to the ATSAMD21E18 that is used in the Trinket M0. The advantage is that this board has all the pins broken out and is a very similar size to the Trinket footprint. The Tau is open source hardware so you can modify as needed.  http://rabidprototypes.com/product/tau/

**Comment by ladyada** [comment]
thanks - im closing this because it's a suggestion not an issue :)
