### ISSUE TITLE
Chip selection issue

### ISSUE THREAD

**Issue by DesmondZuo** [adafruit/Adafruit-Trinket-M0-PCB#4]
Hi! I'm trying to use the trinket m0 chip for my own project, and I ran into the following issue:

I detached the ATSAMD21E18A-U chip from the Trinket M0 and soldered onto my own board.
It can be detected by the arduino IDE program and write program into it, works correctly

However, I purchased the same chip from Digikey (ATSAMD21E18A-MUT), but has the same print of "ATSAMD21E18A-U" on the chip, it does not work. The Arduino IDE does not recognize this chip as an adafruit chip

There are variations on Digikey such as ATSAMD21E18A-AUT, I'm not sure which one I should use.
My goal is to use Arduino IDE and let it detect my purchased chip just like the adafruit detached ones.

Anyone have some ideas on that? Thanks a lot in advance!!

**Comment by tannewt** [comment]
You'll need to install a bootloader on the new chip. Adafruit does it during test. https://github.com/adafruit/uf2-samdx1

**Comment by caternuson** [comment]
This guide covers the how, fwiw:
https://learn.adafruit.com/how-to-program-samd-bootloaders/overview
